<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LearnStore.Domain\LearnStore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="FluentValidation" />
    <Using Include="LearnStore.Application.Commands" />
    <Using Include="LearnStore.Application.DTO" />
    <Using Include="LearnStore.Application.Interfaces" />
    <Using Include="LearnStore.Application.Mappers" />
    <Using Include="LearnStore.Application.Queries" />
    <Using Include="LearnStore.Domain.Entities" />
    <Using Include="LearnStore.Domain.Enums" />
    <Using Include="LearnStore.Domain.Interfaces" />
    <Using Include="LearnStore.Domain.ValueObjects" />
    <Using Include="MediatR" />
    <Using Include="System.Text" />
  </ItemGroup>

</Project>
