<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DataAccess\**" />
    <Compile Remove="Extensions\**" />
    <Compile Remove="Implementations\**" />
    <EmbeddedResource Remove="DataAccess\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="Implementations\**" />
    <None Remove="DataAccess\**" />
    <None Remove="Extensions\**" />
    <None Remove="Implementations\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LearnStore.Domain\LearnStore.Domain.csproj" />
  </ItemGroup>

</Project>
