<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DataAccess\**" />
    <Compile Remove="Implementations\**" />
    <EmbeddedResource Remove="DataAccess\**" />
    <EmbeddedResource Remove="Implementations\**" />
    <None Remove="DataAccess\**" />
    <None Remove="Implementations\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="microsoft.EntityFrameworkCore.SQLServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LearnStore.Domain\LearnStore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include=" Microsoft.EntityFrameworkCore" />
    <Using Include="LearnStore.Domain.Entities" />
    <Using Include="LearnStore.Domain.Enums" />
    <Using Include="LearnStore.Domain.Interfaces" />
    <Using Include="LearnStore.Domain.ValueObjects" />
    <Using Include="LearnStore.Infrastructure.Interfaces" />
    <Using Include="Microsoft.EntityFrameworkCore.Design" />
    <Using Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

</Project>
