<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.18.1" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LearnStore.Application\LearnStore.Application.csproj" />
    <ProjectReference Include="..\LearnStore.Domain\LearnStore.Domain.csproj" />
    <ProjectReference Include="..\LearnStore.Infrastructur\LearnStore.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="AutoFixture" />
    <Using Include="Bogus" />
    <Using Include="FluentAssertions" />
    <Using Include="LearnStore.Application.Commands" />
    <Using Include="LearnStore.Application.DTO" />
    <Using Include="LearnStore.Application.Interfaces" />
    <Using Include="LearnStore.Application.Mappers" />
    <Using Include="LearnStore.Application.Validators" />
    <Using Include="LearnStore.Domain.Entities" />
    <Using Include="LearnStore.Domain.Enums" />
    <Using Include="Xunit" />
  </ItemGroup>

</Project>