services:
  api:
    image: localhost:5000/learnstore-api:latest
    environment:
      DOTNET_ENVIRONMENT: "Production"
    secrets:
      - mssql_sa_password
      - migrator_password
      - app_password
      - identity_password
      - identitymigrator_password
      - FakePaymentGatewayKey
      - JwtKey
    ports:
      - "5003:8080"
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  mssql_sa_password:
    external: true
  migrator_password:
    external: true
  app_password:
    external: true
  identity_password:
    external: true
  identitymigrator_password:
    external: true
  FakePaymentGatewayKey:
    external: true
  JwtKey:
    external: true