//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnStore.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebAppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebAppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnStore.Localization.Resources.WebAppResource", typeof(WebAppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс акаунту.
        /// </summary>
        public static string AccountBalanceLb {
            get {
                return ResourceManager.GetString("AccountBalanceLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати товар.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати товар.
        /// </summary>
        public static string AddProductBtn {
            get {
                return ResourceManager.GetString("AddProductBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Під час входу сталася помилка..
        /// </summary>
        public static string AuthLoginFailed {
            get {
                return ResourceManager.GetString("AuthLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор є обов&apos;язковим..
        /// </summary>
        public static string AuthorIdRequired {
            get {
                return ResourceManager.GetString("AuthorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Під час реєстрації сталася помилка..
        /// </summary>
        public static string AuthRegistrationFailed {
            get {
                return ResourceManager.GetString("AuthRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На головну.
        /// </summary>
        public static string BackToHomeBtn {
            get {
                return ResourceManager.GetString("BackToHomeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія є обов&apos;язковою..
        /// </summary>
        public static string CategoryIdRequired {
            get {
                return ResourceManager.GetString("CategoryIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дочірні товари.
        /// </summary>
        public static string ChildProducts {
            get {
                return ResourceManager.GetString("ChildProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити.
        /// </summary>
        public static string ClearSearchBtn {
            get {
                return ResourceManager.GetString("ClearSearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати профіль.
        /// </summary>
        public static string EditProfileBtn {
            get {
                return ResourceManager.GetString("EditProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле електронної пошти є обов&apos;язковим..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string FileLabel {
            get {
                return ResourceManager.GetString("FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний формат електронної пошти..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний логін або пароль..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введено некоректний номер телефону..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ел. пошта.
        /// </summary>
        public static string LoginLbEmail {
            get {
                return ResourceManager.GetString("LoginLbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string LoginLbPassword {
            get {
                return ResourceManager.GetString("LoginLbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей клієнт ще не придбав жодного товару..
        /// </summary>
        public static string MessageCustomerHasNoPurchases {
            get {
                return ResourceManager.GetString("MessageCustomerHasNoPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У цього продавця немає товарів..
        /// </summary>
        public static string MessageSellerHasNoProducts {
            get {
                return ResourceManager.GetString("MessageSellerHasNoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мій кабінет.
        /// </summary>
        public static string MyAccountBtn {
            get {
                return ResourceManager.GetString("MyAccountBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле імені є обов&apos;язковим..
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товарів немає.
        /// </summary>
        public static string NoProductsAvailable {
            get {
                return ResourceManager.GetString("NoProductsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле пароля є обов&apos;язковим..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролі не збігаються..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефону є обов&apos;язковим..
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна є обов&apos;язковою..
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детальніше.
        /// </summary>
        public static string ProductDetailsBtn {
            get {
                return ResourceManager.GetString("ProductDetailsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей продукт вам не належить..
        /// </summary>
        public static string ProductNotOwnedByUser {
            get {
                return ResourceManager.GetString("ProductNotOwnedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Придбані товари.
        /// </summary>
        public static string PurchasedProductsLb {
            get {
                return ResourceManager.GetString("PurchasedProductsLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструватися як клієнт.
        /// </summary>
        public static string RegisterAsCustomer {
            get {
                return ResourceManager.GetString("RegisterAsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструватися як продавець.
        /// </summary>
        public static string RegisterAsSeller {
            get {
                return ResourceManager.GetString("RegisterAsSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструватися.
        /// </summary>
        public static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердження пароля.
        /// </summary>
        public static string RegisterLbConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterLbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ел.пошту.
        /// </summary>
        public static string RegisterLbEmail {
            get {
                return ResourceManager.GetString("RegisterLbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ім&apos;я користувача.
        /// </summary>
        public static string RegisterLbName {
            get {
                return ResourceManager.GetString("RegisterLbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть пароль.
        /// </summary>
        public static string RegisterLbPassword {
            get {
                return ResourceManager.GetString("RegisterLbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефону.
        /// </summary>
        public static string RegisterLbPhone {
            get {
                return ResourceManager.GetString("RegisterLbPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук серед придбаних товарів.
        /// </summary>
        public static string SearchPurchasedProductsLb {
            get {
                return ResourceManager.GetString("SearchPurchasedProductsLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл є обов&apos;язковим..
        /// </summary>
        public static string UploadFileRequired {
            get {
                return ResourceManager.GetString("UploadFileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вивести кошти.
        /// </summary>
        public static string WithdrawBalanceBtn {
            get {
                return ResourceManager.GetString("WithdrawBalanceBtn", resourceCulture);
            }
        }
    }
}
