<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="LearnStore.Domain.Entities" />
    <Using Include="LearnStore.Domain.Enums" />
    <Using Include="LearnStore.Domain.ValueObjects" />
  </ItemGroup>

</Project>
